server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_get
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
            - After=2020-04-27T20:24:21.756+08:00[Asia/Shanghai]

        - id: payment_create
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/create/**
            - Method=POST

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka




