server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com   # eureka 服务端实例名
  client:
    register-with-eureka: false   # 不向eureka注册自己
    fetch-registry: false          # 不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
